name: translator_proto
description: Dual-mode translator prototype
publish_to: 'none'
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  flutter_tts: ^3.5.2
  connectivity_plus: ^3.0.3
  http: ^0.13.5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true